version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    filter:
      # ignore 'Feedback' PR
      - do: payload
        pull_request:
          title:
            must_exclude:
              regex: ^Feedback$
              regex_flag: none
    validate:
      - do: description
        no_empty:
          enabled: true
          message: "Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed."
      - do: approvals
        min:
          count: 1
        required:
          assignees: true

  - when: pull_request.opened
    name: "Remind about contributing guidelines"
    validate: [ ]
    pass:
      - do: comment
        payload:
          body: >
            Thanks for creating a pull request! Please, check that your pull request meets the [CONTRIBUTING](./CONTRIBUTING.md) requirements.
