name: Run full build

on:
  push:
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Print coverage report
        env:
          report_path: app/build/coverage/test/jacocoTestReport.csv
          run: |
            awk -F"," '{ instructions += $4 + $5; covered += $5; branches += $6 + $7; branches_covered +=$7 } END { print "Instructions covered:", covered"/"instructions, "--", 100*covered/instructions"%"; print "Branches covered:", branches_covered"/"branches, "--", 100*branches_covered/branches"%" }' $report_path

      - name: Create fat .jar file on main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./gradlew app:buildFatJar

      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: All in one jar
          path: app/build/libs/app-all.jar

      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: Upload coverage report
          path: app/build/coverage/test/*