name: Run full build

on:
  push:
jobs:
  build-gradle-project:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: Upload coverage report
          path: app/build/coverage/test/*