name: Run full build

on:
  push:
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Create fat .jar file on main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./gradlew app:buildFatJar

      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: All in one jar
          path: app/build/libs/app-all.jar

      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: Binary search trees lib jar
          path: binary-search-trees/build/libs/binary-search-trees.jar