name: Run full build

on:
  push:
    branches:
      - main
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: |
            app/build/libs
            binary-search-trees/build/libs